### PR TITLE
updated fct_orders

### PR DESCRIPTION
**Pull request by matt-winkler**

### CODE REVIEW

**Comment by matt-winkler** [comment]
@harshjets @kbrock91 I'd appreciate your sense check on this PR. I noticed Harsh added the `example/` folder to the project recently, and some of the tests are failing on there. However, that may be the intent! 

Otherwise, this appears to fix the error that was occurring on the `fct_orders_incremental` model.

**Comment by matt-winkler** [comment]
@kbrock91 looks like `my_first_dbt_model` *does not* create an `id` column anymore, as the final `select` outputs a row_count.

image

**Comment by harshjets** [comment]
I haven't added tests to the /example folder. I am working on a new dataset. Let me have a look.

**Comment by matt-winkler** [comment]
@harshjets @kbrock91 Found where the row_count was and removed it so tests are passing now.

**Pull request merged**
